title: Signified
description: Open source software for fun and profit.
baseurl: ""
url: "https://signified.com.au"

defaults:
  - scope:
      path: "*"
    values:
      layout: "default"

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Rakefile
  - README.md
