title: Signified
description:
baseurl: ""
url: "https://signified.com.au"

defaults:
  - scope:
      path: "*"
    values:
      layout: default

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
